(()=>{
const style=document.createElement('style');style.textContent='.paymentLabel{display:block;margin:14px 0 7px;color:var(--muted);font-size:11px;font-weight:800;letter-spacing:.45px}.paytag{display:inline-flex;align-items:center;margin-top:4px;padding:3px 7px;border:1px solid #344451;border-radius:999px;color:#cbd2d8;font-size:10px;font-weight:750;background:#0b141d}.payGrid{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin:12px 0 4px}.payCard{background:linear-gradient(145deg,#111b25,#0e161f);border:1px solid var(--line);border-radius:14px;padding:12px}.payCard strong{display:block;color:var(--gold);font-size:16px}.payCard span{display:block;margin-top:4px;color:var(--muted);font-size:10px;font-weight:750;letter-spacing:.35px}';document.head.appendChild(style);
const customer=el('customer');if(customer&&!el('payment')){const label=document.createElement('label');label.className='paymentLabel';label.htmlFor='payment';label.textContent='FORMA DE PAGAMENTO';const select=document.createElement('select');select.id='payment';select.innerHTML='<option value="">Selecione...</option><option value="Pix">Pix</option><option value="Débito">Débito</option><option value="Crédito">Crédito</option><option value="Dinheiro">Dinheiro</option>';customer.insertAdjacentElement('afterend',select);select.insertAdjacentElement('beforebegin',label)}
const clientsTitle=[...document.querySelectorAll('#reportPage .subhead')].find(x=>x.textContent.trim()==='CLIENTES');if(clientsTitle&&!el('paymentBreakdown')){const title=document.createElement('div');title.className='subhead';title.textContent='FORMAS DE PAGAMENTO';const grid=document.createElement('div');grid.className='payGrid';grid.id='paymentBreakdown';clientsTitle.parentNode.insertBefore(title,clientsTitle);clientsTitle.parentNode.insertBefore(grid,clientsTitle)}
const baseOpenNew=openNewAccount;window.openNewAccount=function(){baseOpenNew();el('payment').value=''};
const baseOpenExisting=openExistingAccount;window.openExistingAccount=function(i){baseOpenExisting(i);el('payment').value=sales[i].payment||''};
window.saveAccount=function(){if(!el('customer').value.trim())return alert('Informe o nome do cliente.');if(!el('payment').value)return alert('Selecione a forma de pagamento.');const t=calc();if(!t)return alert('Adicione ao menos um produto.');const account={name:el('customer').value.trim(),payment:el('payment').value,total:t,createdAt:editingIndex===null?localDateKey():(sales[editingIndex].createdAt||localDateKey()),items:catalog.map((p,i)=>({name:p.name,qty:qty[i]||0,price:Number(p.price)})).filter(x=>x.qty)};if(editingIndex===null)sales.unshift(account);else sales[editingIndex]=account;saveSales();el('dlg').close();renderHome();renderMonthly();renderDailyReport()};
window.renderHome=function(){const day=localDateKey(),rows=sales.map((s,i)=>({s,i})).filter(x=>x.s.createdAt===day);el('count').textContent=rows.length;el('revenue').textContent=money(rows.reduce((a,x)=>a+Number(x.s.total||0),0));el('salesList').innerHTML=rows.length?rows.map(({s,i})=>`<div class="sale" onclick="openExistingAccount(${i})"><div class="avatar">${esc(s.name.charAt(0).toUpperCase())}</div><div class="info">${esc(s.name)}<small>${(s.items||[]).reduce((a,b)=>a+Number(b.qty||0),0)} itens <span class="paytag">${esc(s.payment||'Não informado')}</span></small></div><div class="price">${money(s.total)}</div></div>`).join(''):'<div class="empty">Nenhuma venda lançada hoje.</div>'};
window.renderDailyReport=function(){const day=el('dayFilter').value||localDateKey(),rows=sales.filter(s=>s.createdAt===day);el('dayRevenue').textContent=money(rows.reduce((a,s)=>a+Number(s.total||0),0));el('dayAccounts').textContent=rows.length;const pays={'Pix':0,'Débito':0,'Crédito':0,'Dinheiro':0};rows.forEach(s=>{if(pays[s.payment]!==undefined)pays[s.payment]+=Number(s.total||0)});if(el('paymentBreakdown'))el('paymentBreakdown').innerHTML=Object.entries(pays).map(([k,v])=>`<div class="payCard"><strong>${money(v)}</strong><span>${k.toUpperCase()}</span></div>`).join('');el('dayClients').innerHTML=rows.length?rows.map(s=>`<div class="dayRow"><div class="info">${esc(s.name)}<small>${(s.items||[]).reduce((a,b)=>a+Number(b.qty||0),0)} itens <span class="paytag">${esc(s.payment||'Não informado')}</span></small></div><div class="price">${money(s.total)}</div></div>`).join(''):'<div class="empty">Nenhuma venda neste dia.</div>';const prod={};rows.forEach(s=>(s.items||[]).forEach(i=>{if(!prod[i.name])prod[i.name]={qty:0,total:0};prod[i.name].qty+=Number(i.qty||0);prod[i.name].total+=Number(i.qty||0)*Number(i.price||0)}));const items=Object.entries(prod).sort((a,b)=>b[1].total-a[1].total);el('dayProducts').innerHTML=items.length?items.map(([name,v])=>`<div class="productRow"><div class="info">${esc(name)}<small>${v.qty} unidade${v.qty===1?'':'s'}</small></div><div class="price">${money(v.total)}</div></div>`).join(''):'<div class="empty">Nenhum produto vendido.</div>'};
renderHome();renderDailyReport();
})();