(()=>{
const URL='https://yibtlwnxdflogthsnhkwt.supabase.co';
const KEY='sb_publishable_pBmN9oa19zwPdUJPf8hpMA_YDfjU-uf';
const H={'apikey':KEY,'Authorization':'Bearer '+KEY,'Content-Type':'application/json'};
const payToDb=v=>({'Pix':'pix','Débito':'debit','Crédito':'credit','Dinheiro':'cash',pix:'pix',debit:'debit',credit:'credit',cash:'cash'}[v]||null);
const payFromDb=v=>({pix:'Pix',debit:'Débito',credit:'Crédito',cash:'Dinheiro'}[v]||'');
const safeParse=(k,fallback)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??fallback}catch{return fallback}};
const localDate=d=>{if(!d)return'';try{return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(d))}catch{return String(d).slice(0,10)}};
const dateTs=d=>d?`${d}T12:00:00-03:00`:new Date().toISOString();
async function req(path,opt={}){const r=await fetch(URL+'/rest/v1/'+path,{...opt,headers:{...H,...(opt.headers||{})},cache:'no-store'});if(!r.ok)throw new Error(await r.text());if(r.status===204)return null;const t=await r.text();return t?JSON.parse(t):null}
function mark(ok,msg=''){localStorage.setItem('arena-sync-state',ok?'ok':'error');localStorage.setItem('arena-sync-message',msg);localStorage.setItem('arena-supabase-last-sync',new Date().toISOString());}
async function syncCatalog(){let local=safeParse('arena-catalog',[]);let remote=await req('products?select=id,name,category,price,active&order=created_at.asc');if(!remote.length&&local.length){await req('products',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(local.map(p=>({name:p.name,category:p.cat||'outros',price:Number(p.price||0),active:true})))});remote=await req('products?select=id,name,category,price,active&order=created_at.asc')}
if(remote.length){const mapped=remote.filter(p=>p.active!==false).map(p=>({name:p.name,price:Number(p.price||0),cat:p.category||'outros',_supabase_id:p.id}));localStorage.setItem('arena-catalog',JSON.stringify(mapped));localStorage.setItem('arena-catalog-backup',JSON.stringify(mapped));return mapped}return local}
async function pushLocalSales(){let sales=safeParse('arena-sales',[]),changed=false;for(const s of sales){if(!s._supabase_id){s._supabase_id=crypto.randomUUID();changed=true}const status=s.status||'closed';const created=s.createdAt||localDate(new Date());const tab={id:s._supabase_id,customer_name:s.name||'Venda',status:['open','closed','cancelled'].includes(status)?status:'closed',payment_method:payToDb(s.payment),opened_at:dateTs(created),closed_at:status==='closed'?dateTs(s.closedAt||created):null};await req('tabs?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(tab)});await req('tab_items?tab_id=eq.'+encodeURIComponent(s._supabase_id),{method:'DELETE',headers:{Prefer:'return=minimal'}});const items=(s.items||[]).filter(i=>Number(i.qty||0)>0).map(i=>({tab_id:s._supabase_id,product_name:i.name||'Produto',unit_price:Number(i.price||0),quantity:Number(i.qty||1)}));if(items.length)await req('tab_items',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(items)})}
if(changed){localStorage.setItem('arena-sales',JSON.stringify(sales));localStorage.setItem('arena-sales-backup',JSON.stringify(sales))}return sales}
async function pullRemoteSales(){const tabs=await req('tabs?select=id,customer_name,status,payment_method,opened_at,closed_at&order=opened_at.desc');const items=await req('tab_items?select=tab_id,product_name,unit_price,quantity&order=created_at.asc');const by={};for(const i of items)(by[i.tab_id]??=[]).push({name:i.product_name,price:Number(i.unit_price||0),qty:Number(i.quantity||0)});const sales=tabs.map(t=>{const its=by[t.id]||[];return{_supabase_id:t.id,name:t.customer_name,status:t.status,payment:payFromDb(t.payment_method),createdAt:localDate(t.opened_at),closedAt:t.closed_at?localDate(t.closed_at):undefined,items:its,total:its.reduce((a,i)=>a+Number(i.price||0)*Number(i.qty||0),0)}});localStorage.setItem('arena-sales',JSON.stringify(sales));localStorage.setItem('arena-sales-backup',JSON.stringify(sales));return sales}
async function initialSync(){try{await syncCatalog();const local=safeParse('arena-sales',[]);if(local.length)await pushLocalSales();await pullRemoteSales();localStorage.setItem('arena-supabase-connected','1');mark(true);return true}catch(e){mark(false,String(e.message||e));throw e}}
let busy=false;async function syncNow(frame,{push=true}={}){if(busy)return false;busy=true;try{if(push){await syncCatalog();await pushLocalSales()}const before=localStorage.getItem('arena-sales')||'[]';await pullRemoteSales();const after=localStorage.getItem('arena-sales')||'[]';mark(true);if(frame&&after!==before&&frame.contentDocument&&!frame.contentDocument.querySelector('dialog[open]'))frame.contentWindow.location.reload();return true}catch(e){console.error('Arena Nice sync:',e);mark(false,String(e.message||e));return false}finally{busy=false}}
async function backgroundSync(frame){return syncNow(frame,{push:false})}
addEventListener('storage',e=>{if(e.key==='arena-sales'||e.key==='arena-catalog')syncNow(null,{push:true})});
window.ArenaSupabase={initialSync,backgroundSync,syncNow,pushLocalSales,pullRemoteSales};
})();