const CACHE='arena-nice-production-v25';
const APP='/app-v6.html';
const STATIC=['/manifest.webmanifest','/apple-touch-icon.png','/catalog-seed-2026-08-30.js'];

const DESIGN_FIX=`<style id="arena-design-fix-v25">
.lock{position:fixed!important;inset:0!important;z-index:100!important;display:none!important;place-items:center!important;background:var(--bg)!important;padding:22px!important;overflow:auto!important}.lock.active{display:grid!important}.lockCard{width:min(100%,390px)!important;max-width:390px!important;background:#fff!important;border:1px solid var(--line)!important;border-radius:22px!important;padding:25px!important;text-align:center!important;box-shadow:0 24px 70px rgba(16,35,74,.16)!important}.lockCard .brand{margin-bottom:18px!important}.lockCard h2{margin:8px 0 10px!important;font-size:24px!important;color:var(--navy)!important}.lockCard p{margin:0 0 14px!important}.lockCard .pin{width:100%!important;height:52px!important;letter-spacing:10px!important;text-align:center!important;font-size:22px!important;font-weight:900!important;margin:0!important}.lockCard .primary{width:100%!important;height:52px!important;margin-top:10px!important}
.app{width:100%!important;max-width:540px!important;margin:0 auto!important;padding-left:16px!important;padding-right:16px!important}.new{max-width:100%!important}.summary{width:100%!important}.stat{min-width:0!important}.row{max-width:100%!important}.bottom{width:100%!important;max-width:540px!important}.nav{min-width:0!important}.primary,.secondary,.danger,.finish{max-width:100%!important}.checkoutPay{max-width:100%!important}
.date{width:100%!important;text-align:center!important;margin:18px auto 7px!important;font-size:13px!important;line-height:1.35!important;white-space:normal!important}.filter{width:100%!important;max-width:100%!important;margin:18px 0 16px!important}.filter input[type="date"],.filter input[type="month"]{display:block!important;width:100%!important;max-width:100%!important;min-width:0!important;height:48px!important;padding:0 12px!important;border-radius:12px!important;font-size:16px!important;line-height:48px!important;text-align:left!important;box-sizing:border-box!important;-webkit-appearance:none!important;appearance:none!important}
@media(max-width:430px){.brand h1{font-size:40px!important}.brand small{font-size:9px!important;letter-spacing:3.2px!important}.app{padding-left:15px!important;padding-right:15px!important}.new{height:56px!important;font-size:16px!important}.stat{min-height:100px!important;padding:15px!important}.stat strong{font-size:24px!important}.row{padding:13px!important}.bottom{padding-left:7px!important;padding-right:7px!important}.nav{height:58px!important;font-size:9px!important}.nav b{font-size:19px!important}}
/* Android em viewport amplo/"desktop": mantém a mesma interface e corrige apenas a escala visual. */
html.arena-android-wide,html.arena-android-wide body{width:100%!important;max-width:none!important;overflow-x:hidden!important}
html.arena-android-wide body{zoom:1.32!important;width:75.7576%!important;min-height:75.7576vh!important}
html.arena-android-wide .app{max-width:none!important;width:100%!important;margin:0!important;padding-left:14px!important;padding-right:14px!important}
html.arena-android-wide .bottom{left:0!important;transform:none!important;max-width:none!important;width:75.7576vw!important}
html.arena-android-wide dialog{max-width:calc(75.7576vw - 22px)!important}
</style>`;
const SCALE_FIX=`<script id="arena-scale-fix-v25">(function(){try{var ua=navigator.userAgent||'';var isAndroid=/Android/i.test(ua);var wide=window.innerWidth>=700;var physicalNarrow=(screen&&Math.min(screen.width,screen.height)<=600);if(isAndroid&&wide&&physicalNarrow)document.documentElement.classList.add('arena-android-wide')}catch(e){}})();<\/script>`;
const AUTH_FIX=`<script id="arena-auth-fix-v25">(function(){try{if(!localStorage.getItem('arena-device-pin')&&localStorage.getItem('arena-device-authorized'))localStorage.setItem('arena-device-pin','migrated');const l=document.getElementById('lock');if(l&&localStorage.getItem('arena-device-pin'))l.classList.remove('active')}catch(e){}})();<\/script>`;
const DATE_FIX=`<script id="arena-date-fix-v25">(function(){function currentDateKey(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date())}function updateArenaDate(){const el=document.getElementById('date');if(el){const parts=new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(new Date());el.textContent=parts.charAt(0).toUpperCase()+parts.slice(1)}const d=document.getElementById('day');if(d&&!d.dataset.userChanged)d.value=currentDateKey();const m=document.getElementById('month');if(m&&!m.dataset.userChanged)m.value=currentDateKey().slice(0,7)}document.addEventListener('change',function(e){if(e.target&&e.target.id==='day')e.target.dataset.userChanged='1';if(e.target&&e.target.id==='month')e.target.dataset.userChanged='1'});updateArenaDate();setInterval(updateArenaDate,60000)})();<\/script>`;
const CATALOG_LOAD=`<script src="/catalog-seed-2026-08-30.js?v=1"><\/script>`;

async function prepareHtml(response){if(!response||!response.ok)return response;const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;let html=await response.text();html=html.replace('</head>',DESIGN_FIX+SCALE_FIX+'</head>').replace('</body>',AUTH_FIX+DATE_FIX+CATALOG_LOAD+'</body>');const headers=new Headers(response.headers);headers.set('cache-control','no-store');return new Response(html,{status:response.status,statusText:response.statusText,headers})}
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(STATIC)).catch(()=>{}));self.skipWaiting()});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim();const clients=await self.clients.matchAll({type:'window',includeUncontrolled:true});for(const client of clients){try{await client.navigate(client.url)}catch(e){}}})())});
self.addEventListener('message',event=>{if(event.data&&event.data.type==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.hostname.endsWith('supabase.co'))return;if(event.request.mode==='navigate'||event.request.destination==='document'){event.respondWith((async()=>{try{const raw=await fetch(event.request,{cache:'no-store'});const response=await prepareHtml(raw);if(response&&response.ok){const cache=await caches.open(CACHE);await cache.put(APP,response.clone())}return response}catch(e){return(await caches.match(APP))||Response.error()}})());return}event.respondWith((async()=>{try{const response=await fetch(event.request,{cache:'no-store'});if(response&&response.ok&&url.origin===self.location.origin){const cache=await caches.open(CACHE);cache.put(event.request,response.clone()).catch(()=>{})}return response}catch(e){return(await caches.match(event.request))||Response.error()}})())});