const CACHE='arena-nice-production-v31';
const APP='/app-v6.html';
const STATIC=['/manifest.webmanifest','/apple-touch-icon.png','/catalog-seed-2026-08-30.js','/vip-portaria-2026-08-30.js'];
const FIX=`<style id="arena-mobile-v31">
html.arena-mobile-force,html.arena-mobile-force body{margin:0!important;max-width:none!important;overflow-x:hidden!important}
html.arena-mobile-force body{zoom:2.45!important;width:40.8163%!important;min-height:40.8163vh!important}
html.arena-mobile-force .app{width:100%!important;max-width:none!important;margin:0!important;padding-left:14px!important;padding-right:14px!important}
html.arena-mobile-force .bottom{left:0!important;transform:none!important;width:40.8163vw!important;max-width:none!important}
html.arena-mobile-force dialog{max-width:calc(40.8163vw - 20px)!important}
</style><script id="arena-mobile-v31-script">(function(){try{var touch=(navigator.maxTouchPoints||0)>0||'ontouchstart'in window;var w=window.innerWidth||document.documentElement.clientWidth||0;if(touch&&w>650)document.documentElement.classList.add('arena-mobile-force')}catch(e){}})();<\/script>`;
const AUTH=`<script>(function(){try{if(!localStorage.getItem('arena-device-pin')&&localStorage.getItem('arena-device-authorized'))localStorage.setItem('arena-device-pin','migrated');var l=document.getElementById('lock');if(l&&localStorage.getItem('arena-device-pin'))l.classList.remove('active')}catch(e){}})();<\/script>`;
const DATE=`<script>(function(){function k(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date())}function u(){var e=document.getElementById('date');if(e){var p=new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(new Date());e.textContent=p.charAt(0).toUpperCase()+p.slice(1)}var d=document.getElementById('day');if(d&&!d.dataset.userChanged)d.value=k();var m=document.getElementById('month');if(m&&!m.dataset.userChanged)m.value=k().slice(0,7)}document.addEventListener('change',function(e){if(e.target&&(e.target.id==='day'||e.target.id==='month'))e.target.dataset.userChanged='1'});u();setInterval(u,60000)})();<\/script>`;
const LOADS=`<script src="/catalog-seed-2026-08-30.js?v=1"><\/script><script src="/vip-portaria-2026-08-30.js?v=1"><\/script>`;
async function prep(r){if(!r||!r.ok)return r;const t=r.headers.get('content-type')||'';if(!t.includes('text/html'))return r;let h=await r.text();h=h.replace('</head>',FIX+'</head>').replace('</body>',AUTH+DATE+LOADS+'</body>');const hd=new Headers(r.headers);hd.set('cache-control','no-store');return new Response(h,{status:r.status,statusText:r.statusText,headers:hd})}
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(c=>c.addAll(STATIC)).catch(()=>{}));self.skipWaiting()});
self.addEventListener('activate',e=>{e.waitUntil((async()=>{for(const k of await caches.keys())if(k!==CACHE)await caches.delete(k);await self.clients.claim();for(const c of await self.clients.matchAll({type:'window',includeUncontrolled:true})){try{await c.navigate(c.url)}catch(_){}}})())});
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(u.hostname.endsWith('supabase.co'))return;if(e.request.mode==='navigate'||e.request.destination==='document'){e.respondWith((async()=>{try{const r=await prep(await fetch(e.request,{cache:'no-store'}));if(r&&r.ok)(await caches.open(CACHE)).put(APP,r.clone()).catch(()=>{});return r}catch(_){return(await caches.match(APP))||Response.error()}})());return}e.respondWith(fetch(e.request,{cache:'no-store'}).catch(()=>caches.match(e.request)))});